name: Example Build Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install .NET 10 Preview
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x-preview

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build
